// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BatchToSpaceNDOptionsT struct {
}

func (t *BatchToSpaceNDOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	BatchToSpaceNDOptionsStart(builder)
	return BatchToSpaceNDOptionsEnd(builder)
}

func (rcv *BatchToSpaceNDOptions) UnPackTo(t *BatchToSpaceNDOptionsT) {
}

func (rcv *BatchToSpaceNDOptions) UnPack() *BatchToSpaceNDOptionsT {
	if rcv == nil { return nil }
	t := &BatchToSpaceNDOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type BatchToSpaceNDOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsBatchToSpaceNDOptions(buf []byte, offset flatbuffers.UOffsetT) *BatchToSpaceNDOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BatchToSpaceNDOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BatchToSpaceNDOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BatchToSpaceNDOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func BatchToSpaceNDOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func BatchToSpaceNDOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
