// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	"strconv"

	flatbuffers "github.com/google/flatbuffers/go"
)

type BuiltinOptions byte

const (
	BuiltinOptionsNONE                              BuiltinOptions = 0
	BuiltinOptionsConv2DOptions                     BuiltinOptions = 1
	BuiltinOptionsDepthwiseConv2DOptions            BuiltinOptions = 2
	BuiltinOptionsConcatEmbeddingsOptions           BuiltinOptions = 3
	BuiltinOptionsLSHProjectionOptions              BuiltinOptions = 4
	BuiltinOptionsPool2DOptions                     BuiltinOptions = 5
	BuiltinOptionsSVDFOptions                       BuiltinOptions = 6
	BuiltinOptionsRNNOptions                        BuiltinOptions = 7
	BuiltinOptionsFullyConnectedOptions             BuiltinOptions = 8
	BuiltinOptionsSoftmaxOptions                    BuiltinOptions = 9
	BuiltinOptionsConcatenationOptions              BuiltinOptions = 10
	BuiltinOptionsAddOptions                        BuiltinOptions = 11
	BuiltinOptionsL2NormOptions                     BuiltinOptions = 12
	BuiltinOptionsLocalResponseNormalizationOptions BuiltinOptions = 13
	BuiltinOptionsLSTMOptions                       BuiltinOptions = 14
	BuiltinOptionsResizeBilinearOptions             BuiltinOptions = 15
	BuiltinOptionsCallOptions                       BuiltinOptions = 16
	BuiltinOptionsReshapeOptions                    BuiltinOptions = 17
	BuiltinOptionsSkipGramOptions                   BuiltinOptions = 18
	BuiltinOptionsSpaceToDepthOptions               BuiltinOptions = 19
	BuiltinOptionsEmbeddingLookupSparseOptions      BuiltinOptions = 20
	BuiltinOptionsMulOptions                        BuiltinOptions = 21
	BuiltinOptionsPadOptions                        BuiltinOptions = 22
	BuiltinOptionsGatherOptions                     BuiltinOptions = 23
	BuiltinOptionsBatchToSpaceNDOptions             BuiltinOptions = 24
	BuiltinOptionsSpaceToBatchNDOptions             BuiltinOptions = 25
	BuiltinOptionsTransposeOptions                  BuiltinOptions = 26
	BuiltinOptionsReducerOptions                    BuiltinOptions = 27
	BuiltinOptionsSubOptions                        BuiltinOptions = 28
	BuiltinOptionsDivOptions                        BuiltinOptions = 29
	BuiltinOptionsSqueezeOptions                    BuiltinOptions = 30
	BuiltinOptionsSequenceRNNOptions                BuiltinOptions = 31
	BuiltinOptionsStridedSliceOptions               BuiltinOptions = 32
	BuiltinOptionsExpOptions                        BuiltinOptions = 33
	BuiltinOptionsTopKV2Options                     BuiltinOptions = 34
	BuiltinOptionsSplitOptions                      BuiltinOptions = 35
	BuiltinOptionsLogSoftmaxOptions                 BuiltinOptions = 36
	BuiltinOptionsCastOptions                       BuiltinOptions = 37
	BuiltinOptionsDequantizeOptions                 BuiltinOptions = 38
	BuiltinOptionsMaximumMinimumOptions             BuiltinOptions = 39
	BuiltinOptionsArgMaxOptions                     BuiltinOptions = 40
	BuiltinOptionsLessOptions                       BuiltinOptions = 41
	BuiltinOptionsNegOptions                        BuiltinOptions = 42
	BuiltinOptionsPadV2Options                      BuiltinOptions = 43
	BuiltinOptionsGreaterOptions                    BuiltinOptions = 44
	BuiltinOptionsGreaterEqualOptions               BuiltinOptions = 45
	BuiltinOptionsLessEqualOptions                  BuiltinOptions = 46
	BuiltinOptionsSelectOptions                     BuiltinOptions = 47
	BuiltinOptionsSliceOptions                      BuiltinOptions = 48
	BuiltinOptionsTransposeConvOptions              BuiltinOptions = 49
	BuiltinOptionsSparseToDenseOptions              BuiltinOptions = 50
	BuiltinOptionsTileOptions                       BuiltinOptions = 51
	BuiltinOptionsExpandDimsOptions                 BuiltinOptions = 52
	BuiltinOptionsEqualOptions                      BuiltinOptions = 53
	BuiltinOptionsNotEqualOptions                   BuiltinOptions = 54
	BuiltinOptionsShapeOptions                      BuiltinOptions = 55
	BuiltinOptionsPowOptions                        BuiltinOptions = 56
	BuiltinOptionsArgMinOptions                     BuiltinOptions = 57
	BuiltinOptionsFakeQuantOptions                  BuiltinOptions = 58
	BuiltinOptionsPackOptions                       BuiltinOptions = 59
	BuiltinOptionsLogicalOrOptions                  BuiltinOptions = 60
	BuiltinOptionsOneHotOptions                     BuiltinOptions = 61
	BuiltinOptionsLogicalAndOptions                 BuiltinOptions = 62
	BuiltinOptionsLogicalNotOptions                 BuiltinOptions = 63
	BuiltinOptionsUnpackOptions                     BuiltinOptions = 64
	BuiltinOptionsFloorDivOptions                   BuiltinOptions = 65
	BuiltinOptionsSquareOptions                     BuiltinOptions = 66
	BuiltinOptionsZerosLikeOptions                  BuiltinOptions = 67
	BuiltinOptionsFillOptions                       BuiltinOptions = 68
	BuiltinOptionsBidirectionalSequenceLSTMOptions  BuiltinOptions = 69
	BuiltinOptionsBidirectionalSequenceRNNOptions   BuiltinOptions = 70
	BuiltinOptionsUnidirectionalSequenceLSTMOptions BuiltinOptions = 71
	BuiltinOptionsFloorModOptions                   BuiltinOptions = 72
	BuiltinOptionsRangeOptions                      BuiltinOptions = 73
	BuiltinOptionsResizeNearestNeighborOptions      BuiltinOptions = 74
	BuiltinOptionsLeakyReluOptions                  BuiltinOptions = 75
	BuiltinOptionsSquaredDifferenceOptions          BuiltinOptions = 76
	BuiltinOptionsMirrorPadOptions                  BuiltinOptions = 77
	BuiltinOptionsAbsOptions                        BuiltinOptions = 78
	BuiltinOptionsSplitVOptions                     BuiltinOptions = 79
	BuiltinOptionsUniqueOptions                     BuiltinOptions = 80
	BuiltinOptionsReverseV2Options                  BuiltinOptions = 81
	BuiltinOptionsAddNOptions                       BuiltinOptions = 82
	BuiltinOptionsGatherNdOptions                   BuiltinOptions = 83
	BuiltinOptionsCosOptions                        BuiltinOptions = 84
	BuiltinOptionsWhereOptions                      BuiltinOptions = 85
	BuiltinOptionsRankOptions                       BuiltinOptions = 86
	BuiltinOptionsReverseSequenceOptions            BuiltinOptions = 87
	BuiltinOptionsMatrixDiagOptions                 BuiltinOptions = 88
	BuiltinOptionsQuantizeOptions                   BuiltinOptions = 89
	BuiltinOptionsMatrixSetDiagOptions              BuiltinOptions = 90
	BuiltinOptionsHardSwishOptions                  BuiltinOptions = 91
	BuiltinOptionsIfOptions                         BuiltinOptions = 92
	BuiltinOptionsWhileOptions                      BuiltinOptions = 93
	BuiltinOptionsDepthToSpaceOptions               BuiltinOptions = 94
	BuiltinOptionsNonMaxSuppressionV4Options        BuiltinOptions = 95
	BuiltinOptionsNonMaxSuppressionV5Options        BuiltinOptions = 96
	BuiltinOptionsScatterNdOptions                  BuiltinOptions = 97
	BuiltinOptionsSelectV2Options                   BuiltinOptions = 98
	BuiltinOptionsDensifyOptions                    BuiltinOptions = 99
	BuiltinOptionsSegmentSumOptions                 BuiltinOptions = 100
	BuiltinOptionsBatchMatMulOptions                BuiltinOptions = 101
	BuiltinOptionsCumsumOptions                     BuiltinOptions = 102
)

var EnumNamesBuiltinOptions = map[BuiltinOptions]string{
	BuiltinOptionsNONE:                              "NONE",
	BuiltinOptionsConv2DOptions:                     "Conv2DOptions",
	BuiltinOptionsDepthwiseConv2DOptions:            "DepthwiseConv2DOptions",
	BuiltinOptionsConcatEmbeddingsOptions:           "ConcatEmbeddingsOptions",
	BuiltinOptionsLSHProjectionOptions:              "LSHProjectionOptions",
	BuiltinOptionsPool2DOptions:                     "Pool2DOptions",
	BuiltinOptionsSVDFOptions:                       "SVDFOptions",
	BuiltinOptionsRNNOptions:                        "RNNOptions",
	BuiltinOptionsFullyConnectedOptions:             "FullyConnectedOptions",
	BuiltinOptionsSoftmaxOptions:                    "SoftmaxOptions",
	BuiltinOptionsConcatenationOptions:              "ConcatenationOptions",
	BuiltinOptionsAddOptions:                        "AddOptions",
	BuiltinOptionsL2NormOptions:                     "L2NormOptions",
	BuiltinOptionsLocalResponseNormalizationOptions: "LocalResponseNormalizationOptions",
	BuiltinOptionsLSTMOptions:                       "LSTMOptions",
	BuiltinOptionsResizeBilinearOptions:             "ResizeBilinearOptions",
	BuiltinOptionsCallOptions:                       "CallOptions",
	BuiltinOptionsReshapeOptions:                    "ReshapeOptions",
	BuiltinOptionsSkipGramOptions:                   "SkipGramOptions",
	BuiltinOptionsSpaceToDepthOptions:               "SpaceToDepthOptions",
	BuiltinOptionsEmbeddingLookupSparseOptions:      "EmbeddingLookupSparseOptions",
	BuiltinOptionsMulOptions:                        "MulOptions",
	BuiltinOptionsPadOptions:                        "PadOptions",
	BuiltinOptionsGatherOptions:                     "GatherOptions",
	BuiltinOptionsBatchToSpaceNDOptions:             "BatchToSpaceNDOptions",
	BuiltinOptionsSpaceToBatchNDOptions:             "SpaceToBatchNDOptions",
	BuiltinOptionsTransposeOptions:                  "TransposeOptions",
	BuiltinOptionsReducerOptions:                    "ReducerOptions",
	BuiltinOptionsSubOptions:                        "SubOptions",
	BuiltinOptionsDivOptions:                        "DivOptions",
	BuiltinOptionsSqueezeOptions:                    "SqueezeOptions",
	BuiltinOptionsSequenceRNNOptions:                "SequenceRNNOptions",
	BuiltinOptionsStridedSliceOptions:               "StridedSliceOptions",
	BuiltinOptionsExpOptions:                        "ExpOptions",
	BuiltinOptionsTopKV2Options:                     "TopKV2Options",
	BuiltinOptionsSplitOptions:                      "SplitOptions",
	BuiltinOptionsLogSoftmaxOptions:                 "LogSoftmaxOptions",
	BuiltinOptionsCastOptions:                       "CastOptions",
	BuiltinOptionsDequantizeOptions:                 "DequantizeOptions",
	BuiltinOptionsMaximumMinimumOptions:             "MaximumMinimumOptions",
	BuiltinOptionsArgMaxOptions:                     "ArgMaxOptions",
	BuiltinOptionsLessOptions:                       "LessOptions",
	BuiltinOptionsNegOptions:                        "NegOptions",
	BuiltinOptionsPadV2Options:                      "PadV2Options",
	BuiltinOptionsGreaterOptions:                    "GreaterOptions",
	BuiltinOptionsGreaterEqualOptions:               "GreaterEqualOptions",
	BuiltinOptionsLessEqualOptions:                  "LessEqualOptions",
	BuiltinOptionsSelectOptions:                     "SelectOptions",
	BuiltinOptionsSliceOptions:                      "SliceOptions",
	BuiltinOptionsTransposeConvOptions:              "TransposeConvOptions",
	BuiltinOptionsSparseToDenseOptions:              "SparseToDenseOptions",
	BuiltinOptionsTileOptions:                       "TileOptions",
	BuiltinOptionsExpandDimsOptions:                 "ExpandDimsOptions",
	BuiltinOptionsEqualOptions:                      "EqualOptions",
	BuiltinOptionsNotEqualOptions:                   "NotEqualOptions",
	BuiltinOptionsShapeOptions:                      "ShapeOptions",
	BuiltinOptionsPowOptions:                        "PowOptions",
	BuiltinOptionsArgMinOptions:                     "ArgMinOptions",
	BuiltinOptionsFakeQuantOptions:                  "FakeQuantOptions",
	BuiltinOptionsPackOptions:                       "PackOptions",
	BuiltinOptionsLogicalOrOptions:                  "LogicalOrOptions",
	BuiltinOptionsOneHotOptions:                     "OneHotOptions",
	BuiltinOptionsLogicalAndOptions:                 "LogicalAndOptions",
	BuiltinOptionsLogicalNotOptions:                 "LogicalNotOptions",
	BuiltinOptionsUnpackOptions:                     "UnpackOptions",
	BuiltinOptionsFloorDivOptions:                   "FloorDivOptions",
	BuiltinOptionsSquareOptions:                     "SquareOptions",
	BuiltinOptionsZerosLikeOptions:                  "ZerosLikeOptions",
	BuiltinOptionsFillOptions:                       "FillOptions",
	BuiltinOptionsBidirectionalSequenceLSTMOptions:  "BidirectionalSequenceLSTMOptions",
	BuiltinOptionsBidirectionalSequenceRNNOptions:   "BidirectionalSequenceRNNOptions",
	BuiltinOptionsUnidirectionalSequenceLSTMOptions: "UnidirectionalSequenceLSTMOptions",
	BuiltinOptionsFloorModOptions:                   "FloorModOptions",
	BuiltinOptionsRangeOptions:                      "RangeOptions",
	BuiltinOptionsResizeNearestNeighborOptions:      "ResizeNearestNeighborOptions",
	BuiltinOptionsLeakyReluOptions:                  "LeakyReluOptions",
	BuiltinOptionsSquaredDifferenceOptions:          "SquaredDifferenceOptions",
	BuiltinOptionsMirrorPadOptions:                  "MirrorPadOptions",
	BuiltinOptionsAbsOptions:                        "AbsOptions",
	BuiltinOptionsSplitVOptions:                     "SplitVOptions",
	BuiltinOptionsUniqueOptions:                     "UniqueOptions",
	BuiltinOptionsReverseV2Options:                  "ReverseV2Options",
	BuiltinOptionsAddNOptions:                       "AddNOptions",
	BuiltinOptionsGatherNdOptions:                   "GatherNdOptions",
	BuiltinOptionsCosOptions:                        "CosOptions",
	BuiltinOptionsWhereOptions:                      "WhereOptions",
	BuiltinOptionsRankOptions:                       "RankOptions",
	BuiltinOptionsReverseSequenceOptions:            "ReverseSequenceOptions",
	BuiltinOptionsMatrixDiagOptions:                 "MatrixDiagOptions",
	BuiltinOptionsQuantizeOptions:                   "QuantizeOptions",
	BuiltinOptionsMatrixSetDiagOptions:              "MatrixSetDiagOptions",
	BuiltinOptionsHardSwishOptions:                  "HardSwishOptions",
	BuiltinOptionsIfOptions:                         "IfOptions",
	BuiltinOptionsWhileOptions:                      "WhileOptions",
	BuiltinOptionsDepthToSpaceOptions:               "DepthToSpaceOptions",
	BuiltinOptionsNonMaxSuppressionV4Options:        "NonMaxSuppressionV4Options",
	BuiltinOptionsNonMaxSuppressionV5Options:        "NonMaxSuppressionV5Options",
	BuiltinOptionsScatterNdOptions:                  "ScatterNdOptions",
	BuiltinOptionsSelectV2Options:                   "SelectV2Options",
	BuiltinOptionsDensifyOptions:                    "DensifyOptions",
	BuiltinOptionsSegmentSumOptions:                 "SegmentSumOptions",
	BuiltinOptionsBatchMatMulOptions:                "BatchMatMulOptions",
	BuiltinOptionsCumsumOptions:                     "CumsumOptions",
}

var EnumValuesBuiltinOptions = map[string]BuiltinOptions{
	"NONE":                              BuiltinOptionsNONE,
	"Conv2DOptions":                     BuiltinOptionsConv2DOptions,
	"DepthwiseConv2DOptions":            BuiltinOptionsDepthwiseConv2DOptions,
	"ConcatEmbeddingsOptions":           BuiltinOptionsConcatEmbeddingsOptions,
	"LSHProjectionOptions":              BuiltinOptionsLSHProjectionOptions,
	"Pool2DOptions":                     BuiltinOptionsPool2DOptions,
	"SVDFOptions":                       BuiltinOptionsSVDFOptions,
	"RNNOptions":                        BuiltinOptionsRNNOptions,
	"FullyConnectedOptions":             BuiltinOptionsFullyConnectedOptions,
	"SoftmaxOptions":                    BuiltinOptionsSoftmaxOptions,
	"ConcatenationOptions":              BuiltinOptionsConcatenationOptions,
	"AddOptions":                        BuiltinOptionsAddOptions,
	"L2NormOptions":                     BuiltinOptionsL2NormOptions,
	"LocalResponseNormalizationOptions": BuiltinOptionsLocalResponseNormalizationOptions,
	"LSTMOptions":                       BuiltinOptionsLSTMOptions,
	"ResizeBilinearOptions":             BuiltinOptionsResizeBilinearOptions,
	"CallOptions":                       BuiltinOptionsCallOptions,
	"ReshapeOptions":                    BuiltinOptionsReshapeOptions,
	"SkipGramOptions":                   BuiltinOptionsSkipGramOptions,
	"SpaceToDepthOptions":               BuiltinOptionsSpaceToDepthOptions,
	"EmbeddingLookupSparseOptions":      BuiltinOptionsEmbeddingLookupSparseOptions,
	"MulOptions":                        BuiltinOptionsMulOptions,
	"PadOptions":                        BuiltinOptionsPadOptions,
	"GatherOptions":                     BuiltinOptionsGatherOptions,
	"BatchToSpaceNDOptions":             BuiltinOptionsBatchToSpaceNDOptions,
	"SpaceToBatchNDOptions":             BuiltinOptionsSpaceToBatchNDOptions,
	"TransposeOptions":                  BuiltinOptionsTransposeOptions,
	"ReducerOptions":                    BuiltinOptionsReducerOptions,
	"SubOptions":                        BuiltinOptionsSubOptions,
	"DivOptions":                        BuiltinOptionsDivOptions,
	"SqueezeOptions":                    BuiltinOptionsSqueezeOptions,
	"SequenceRNNOptions":                BuiltinOptionsSequenceRNNOptions,
	"StridedSliceOptions":               BuiltinOptionsStridedSliceOptions,
	"ExpOptions":                        BuiltinOptionsExpOptions,
	"TopKV2Options":                     BuiltinOptionsTopKV2Options,
	"SplitOptions":                      BuiltinOptionsSplitOptions,
	"LogSoftmaxOptions":                 BuiltinOptionsLogSoftmaxOptions,
	"CastOptions":                       BuiltinOptionsCastOptions,
	"DequantizeOptions":                 BuiltinOptionsDequantizeOptions,
	"MaximumMinimumOptions":             BuiltinOptionsMaximumMinimumOptions,
	"ArgMaxOptions":                     BuiltinOptionsArgMaxOptions,
	"LessOptions":                       BuiltinOptionsLessOptions,
	"NegOptions":                        BuiltinOptionsNegOptions,
	"PadV2Options":                      BuiltinOptionsPadV2Options,
	"GreaterOptions":                    BuiltinOptionsGreaterOptions,
	"GreaterEqualOptions":               BuiltinOptionsGreaterEqualOptions,
	"LessEqualOptions":                  BuiltinOptionsLessEqualOptions,
	"SelectOptions":                     BuiltinOptionsSelectOptions,
	"SliceOptions":                      BuiltinOptionsSliceOptions,
	"TransposeConvOptions":              BuiltinOptionsTransposeConvOptions,
	"SparseToDenseOptions":              BuiltinOptionsSparseToDenseOptions,
	"TileOptions":                       BuiltinOptionsTileOptions,
	"ExpandDimsOptions":                 BuiltinOptionsExpandDimsOptions,
	"EqualOptions":                      BuiltinOptionsEqualOptions,
	"NotEqualOptions":                   BuiltinOptionsNotEqualOptions,
	"ShapeOptions":                      BuiltinOptionsShapeOptions,
	"PowOptions":                        BuiltinOptionsPowOptions,
	"ArgMinOptions":                     BuiltinOptionsArgMinOptions,
	"FakeQuantOptions":                  BuiltinOptionsFakeQuantOptions,
	"PackOptions":                       BuiltinOptionsPackOptions,
	"LogicalOrOptions":                  BuiltinOptionsLogicalOrOptions,
	"OneHotOptions":                     BuiltinOptionsOneHotOptions,
	"LogicalAndOptions":                 BuiltinOptionsLogicalAndOptions,
	"LogicalNotOptions":                 BuiltinOptionsLogicalNotOptions,
	"UnpackOptions":                     BuiltinOptionsUnpackOptions,
	"FloorDivOptions":                   BuiltinOptionsFloorDivOptions,
	"SquareOptions":                     BuiltinOptionsSquareOptions,
	"ZerosLikeOptions":                  BuiltinOptionsZerosLikeOptions,
	"FillOptions":                       BuiltinOptionsFillOptions,
	"BidirectionalSequenceLSTMOptions":  BuiltinOptionsBidirectionalSequenceLSTMOptions,
	"BidirectionalSequenceRNNOptions":   BuiltinOptionsBidirectionalSequenceRNNOptions,
	"UnidirectionalSequenceLSTMOptions": BuiltinOptionsUnidirectionalSequenceLSTMOptions,
	"FloorModOptions":                   BuiltinOptionsFloorModOptions,
	"RangeOptions":                      BuiltinOptionsRangeOptions,
	"ResizeNearestNeighborOptions":      BuiltinOptionsResizeNearestNeighborOptions,
	"LeakyReluOptions":                  BuiltinOptionsLeakyReluOptions,
	"SquaredDifferenceOptions":          BuiltinOptionsSquaredDifferenceOptions,
	"MirrorPadOptions":                  BuiltinOptionsMirrorPadOptions,
	"AbsOptions":                        BuiltinOptionsAbsOptions,
	"SplitVOptions":                     BuiltinOptionsSplitVOptions,
	"UniqueOptions":                     BuiltinOptionsUniqueOptions,
	"ReverseV2Options":                  BuiltinOptionsReverseV2Options,
	"AddNOptions":                       BuiltinOptionsAddNOptions,
	"GatherNdOptions":                   BuiltinOptionsGatherNdOptions,
	"CosOptions":                        BuiltinOptionsCosOptions,
	"WhereOptions":                      BuiltinOptionsWhereOptions,
	"RankOptions":                       BuiltinOptionsRankOptions,
	"ReverseSequenceOptions":            BuiltinOptionsReverseSequenceOptions,
	"MatrixDiagOptions":                 BuiltinOptionsMatrixDiagOptions,
	"QuantizeOptions":                   BuiltinOptionsQuantizeOptions,
	"MatrixSetDiagOptions":              BuiltinOptionsMatrixSetDiagOptions,
	"HardSwishOptions":                  BuiltinOptionsHardSwishOptions,
	"IfOptions":                         BuiltinOptionsIfOptions,
	"WhileOptions":                      BuiltinOptionsWhileOptions,
	"DepthToSpaceOptions":               BuiltinOptionsDepthToSpaceOptions,
	"NonMaxSuppressionV4Options":        BuiltinOptionsNonMaxSuppressionV4Options,
	"NonMaxSuppressionV5Options":        BuiltinOptionsNonMaxSuppressionV5Options,
	"ScatterNdOptions":                  BuiltinOptionsScatterNdOptions,
	"SelectV2Options":                   BuiltinOptionsSelectV2Options,
	"DensifyOptions":                    BuiltinOptionsDensifyOptions,
	"SegmentSumOptions":                 BuiltinOptionsSegmentSumOptions,
	"BatchMatMulOptions":                BuiltinOptionsBatchMatMulOptions,
	"CumsumOptions":                     BuiltinOptionsCumsumOptions,
}

func (v BuiltinOptions) String() string {
	if s, ok := EnumNamesBuiltinOptions[v]; ok {
		return s
	}
	return "BuiltinOptions(" + strconv.FormatInt(int64(v), 10) + ")"
}

type BuiltinOptionsT struct {
	Type BuiltinOptions
	Value interface{}
}

func (t *BuiltinOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case BuiltinOptionsConv2DOptions:
		return t.Value.(*Conv2DOptionsT).Pack(builder)
	case BuiltinOptionsDepthwiseConv2DOptions:
		return t.Value.(*DepthwiseConv2DOptionsT).Pack(builder)
	case BuiltinOptionsConcatEmbeddingsOptions:
		return t.Value.(*ConcatEmbeddingsOptionsT).Pack(builder)
	case BuiltinOptionsLSHProjectionOptions:
		return t.Value.(*LSHProjectionOptionsT).Pack(builder)
	case BuiltinOptionsPool2DOptions:
		return t.Value.(*Pool2DOptionsT).Pack(builder)
	case BuiltinOptionsSVDFOptions:
		return t.Value.(*SVDFOptionsT).Pack(builder)
	case BuiltinOptionsRNNOptions:
		return t.Value.(*RNNOptionsT).Pack(builder)
	case BuiltinOptionsFullyConnectedOptions:
		return t.Value.(*FullyConnectedOptionsT).Pack(builder)
	case BuiltinOptionsSoftmaxOptions:
		return t.Value.(*SoftmaxOptionsT).Pack(builder)
	case BuiltinOptionsConcatenationOptions:
		return t.Value.(*ConcatenationOptionsT).Pack(builder)
	case BuiltinOptionsAddOptions:
		return t.Value.(*AddOptionsT).Pack(builder)
	case BuiltinOptionsL2NormOptions:
		return t.Value.(*L2NormOptionsT).Pack(builder)
	case BuiltinOptionsLocalResponseNormalizationOptions:
		return t.Value.(*LocalResponseNormalizationOptionsT).Pack(builder)
	case BuiltinOptionsLSTMOptions:
		return t.Value.(*LSTMOptionsT).Pack(builder)
	case BuiltinOptionsResizeBilinearOptions:
		return t.Value.(*ResizeBilinearOptionsT).Pack(builder)
	case BuiltinOptionsCallOptions:
		return t.Value.(*CallOptionsT).Pack(builder)
	case BuiltinOptionsReshapeOptions:
		return t.Value.(*ReshapeOptionsT).Pack(builder)
	case BuiltinOptionsSkipGramOptions:
		return t.Value.(*SkipGramOptionsT).Pack(builder)
	case BuiltinOptionsSpaceToDepthOptions:
		return t.Value.(*SpaceToDepthOptionsT).Pack(builder)
	case BuiltinOptionsEmbeddingLookupSparseOptions:
		return t.Value.(*EmbeddingLookupSparseOptionsT).Pack(builder)
	case BuiltinOptionsMulOptions:
		return t.Value.(*MulOptionsT).Pack(builder)
	case BuiltinOptionsPadOptions:
		return t.Value.(*PadOptionsT).Pack(builder)
	case BuiltinOptionsGatherOptions:
		return t.Value.(*GatherOptionsT).Pack(builder)
	case BuiltinOptionsBatchToSpaceNDOptions:
		return t.Value.(*BatchToSpaceNDOptionsT).Pack(builder)
	case BuiltinOptionsSpaceToBatchNDOptions:
		return t.Value.(*SpaceToBatchNDOptionsT).Pack(builder)
	case BuiltinOptionsTransposeOptions:
		return t.Value.(*TransposeOptionsT).Pack(builder)
	case BuiltinOptionsReducerOptions:
		return t.Value.(*ReducerOptionsT).Pack(builder)
	case BuiltinOptionsSubOptions:
		return t.Value.(*SubOptionsT).Pack(builder)
	case BuiltinOptionsDivOptions:
		return t.Value.(*DivOptionsT).Pack(builder)
	case BuiltinOptionsSqueezeOptions:
		return t.Value.(*SqueezeOptionsT).Pack(builder)
	case BuiltinOptionsSequenceRNNOptions:
		return t.Value.(*SequenceRNNOptionsT).Pack(builder)
	case BuiltinOptionsStridedSliceOptions:
		return t.Value.(*StridedSliceOptionsT).Pack(builder)
	case BuiltinOptionsExpOptions:
		return t.Value.(*ExpOptionsT).Pack(builder)
	case BuiltinOptionsTopKV2Options:
		return t.Value.(*TopKV2OptionsT).Pack(builder)
	case BuiltinOptionsSplitOptions:
		return t.Value.(*SplitOptionsT).Pack(builder)
	case BuiltinOptionsLogSoftmaxOptions:
		return t.Value.(*LogSoftmaxOptionsT).Pack(builder)
	case BuiltinOptionsCastOptions:
		return t.Value.(*CastOptionsT).Pack(builder)
	case BuiltinOptionsDequantizeOptions:
		return t.Value.(*DequantizeOptionsT).Pack(builder)
	case BuiltinOptionsMaximumMinimumOptions:
		return t.Value.(*MaximumMinimumOptionsT).Pack(builder)
	case BuiltinOptionsArgMaxOptions:
		return t.Value.(*ArgMaxOptionsT).Pack(builder)
	case BuiltinOptionsLessOptions:
		return t.Value.(*LessOptionsT).Pack(builder)
	case BuiltinOptionsNegOptions:
		return t.Value.(*NegOptionsT).Pack(builder)
	case BuiltinOptionsPadV2Options:
		return t.Value.(*PadV2OptionsT).Pack(builder)
	case BuiltinOptionsGreaterOptions:
		return t.Value.(*GreaterOptionsT).Pack(builder)
	case BuiltinOptionsGreaterEqualOptions:
		return t.Value.(*GreaterEqualOptionsT).Pack(builder)
	case BuiltinOptionsLessEqualOptions:
		return t.Value.(*LessEqualOptionsT).Pack(builder)
	case BuiltinOptionsSelectOptions:
		return t.Value.(*SelectOptionsT).Pack(builder)
	case BuiltinOptionsSliceOptions:
		return t.Value.(*SliceOptionsT).Pack(builder)
	case BuiltinOptionsTransposeConvOptions:
		return t.Value.(*TransposeConvOptionsT).Pack(builder)
	case BuiltinOptionsSparseToDenseOptions:
		return t.Value.(*SparseToDenseOptionsT).Pack(builder)
	case BuiltinOptionsTileOptions:
		return t.Value.(*TileOptionsT).Pack(builder)
	case BuiltinOptionsExpandDimsOptions:
		return t.Value.(*ExpandDimsOptionsT).Pack(builder)
	case BuiltinOptionsEqualOptions:
		return t.Value.(*EqualOptionsT).Pack(builder)
	case BuiltinOptionsNotEqualOptions:
		return t.Value.(*NotEqualOptionsT).Pack(builder)
	case BuiltinOptionsShapeOptions:
		return t.Value.(*ShapeOptionsT).Pack(builder)
	case BuiltinOptionsPowOptions:
		return t.Value.(*PowOptionsT).Pack(builder)
	case BuiltinOptionsArgMinOptions:
		return t.Value.(*ArgMinOptionsT).Pack(builder)
	case BuiltinOptionsFakeQuantOptions:
		return t.Value.(*FakeQuantOptionsT).Pack(builder)
	case BuiltinOptionsPackOptions:
		return t.Value.(*PackOptionsT).Pack(builder)
	case BuiltinOptionsLogicalOrOptions:
		return t.Value.(*LogicalOrOptionsT).Pack(builder)
	case BuiltinOptionsOneHotOptions:
		return t.Value.(*OneHotOptionsT).Pack(builder)
	case BuiltinOptionsLogicalAndOptions:
		return t.Value.(*LogicalAndOptionsT).Pack(builder)
	case BuiltinOptionsLogicalNotOptions:
		return t.Value.(*LogicalNotOptionsT).Pack(builder)
	case BuiltinOptionsUnpackOptions:
		return t.Value.(*UnpackOptionsT).Pack(builder)
	case BuiltinOptionsFloorDivOptions:
		return t.Value.(*FloorDivOptionsT).Pack(builder)
	case BuiltinOptionsSquareOptions:
		return t.Value.(*SquareOptionsT).Pack(builder)
	case BuiltinOptionsZerosLikeOptions:
		return t.Value.(*ZerosLikeOptionsT).Pack(builder)
	case BuiltinOptionsFillOptions:
		return t.Value.(*FillOptionsT).Pack(builder)
	case BuiltinOptionsBidirectionalSequenceLSTMOptions:
		return t.Value.(*BidirectionalSequenceLSTMOptionsT).Pack(builder)
	case BuiltinOptionsBidirectionalSequenceRNNOptions:
		return t.Value.(*BidirectionalSequenceRNNOptionsT).Pack(builder)
	case BuiltinOptionsUnidirectionalSequenceLSTMOptions:
		return t.Value.(*UnidirectionalSequenceLSTMOptionsT).Pack(builder)
	case BuiltinOptionsFloorModOptions:
		return t.Value.(*FloorModOptionsT).Pack(builder)
	case BuiltinOptionsRangeOptions:
		return t.Value.(*RangeOptionsT).Pack(builder)
	case BuiltinOptionsResizeNearestNeighborOptions:
		return t.Value.(*ResizeNearestNeighborOptionsT).Pack(builder)
	case BuiltinOptionsLeakyReluOptions:
		return t.Value.(*LeakyReluOptionsT).Pack(builder)
	case BuiltinOptionsSquaredDifferenceOptions:
		return t.Value.(*SquaredDifferenceOptionsT).Pack(builder)
	case BuiltinOptionsMirrorPadOptions:
		return t.Value.(*MirrorPadOptionsT).Pack(builder)
	case BuiltinOptionsAbsOptions:
		return t.Value.(*AbsOptionsT).Pack(builder)
	case BuiltinOptionsSplitVOptions:
		return t.Value.(*SplitVOptionsT).Pack(builder)
	case BuiltinOptionsUniqueOptions:
		return t.Value.(*UniqueOptionsT).Pack(builder)
	case BuiltinOptionsReverseV2Options:
		return t.Value.(*ReverseV2OptionsT).Pack(builder)
	case BuiltinOptionsAddNOptions:
		return t.Value.(*AddNOptionsT).Pack(builder)
	case BuiltinOptionsGatherNdOptions:
		return t.Value.(*GatherNdOptionsT).Pack(builder)
	case BuiltinOptionsCosOptions:
		return t.Value.(*CosOptionsT).Pack(builder)
	case BuiltinOptionsWhereOptions:
		return t.Value.(*WhereOptionsT).Pack(builder)
	case BuiltinOptionsRankOptions:
		return t.Value.(*RankOptionsT).Pack(builder)
	case BuiltinOptionsReverseSequenceOptions:
		return t.Value.(*ReverseSequenceOptionsT).Pack(builder)
	case BuiltinOptionsMatrixDiagOptions:
		return t.Value.(*MatrixDiagOptionsT).Pack(builder)
	case BuiltinOptionsQuantizeOptions:
		return t.Value.(*QuantizeOptionsT).Pack(builder)
	case BuiltinOptionsMatrixSetDiagOptions:
		return t.Value.(*MatrixSetDiagOptionsT).Pack(builder)
	case BuiltinOptionsHardSwishOptions:
		return t.Value.(*HardSwishOptionsT).Pack(builder)
	case BuiltinOptionsIfOptions:
		return t.Value.(*IfOptionsT).Pack(builder)
	case BuiltinOptionsWhileOptions:
		return t.Value.(*WhileOptionsT).Pack(builder)
	case BuiltinOptionsDepthToSpaceOptions:
		return t.Value.(*DepthToSpaceOptionsT).Pack(builder)
	case BuiltinOptionsNonMaxSuppressionV4Options:
		return t.Value.(*NonMaxSuppressionV4OptionsT).Pack(builder)
	case BuiltinOptionsNonMaxSuppressionV5Options:
		return t.Value.(*NonMaxSuppressionV5OptionsT).Pack(builder)
	case BuiltinOptionsScatterNdOptions:
		return t.Value.(*ScatterNdOptionsT).Pack(builder)
	case BuiltinOptionsSelectV2Options:
		return t.Value.(*SelectV2OptionsT).Pack(builder)
	case BuiltinOptionsDensifyOptions:
		return t.Value.(*DensifyOptionsT).Pack(builder)
	case BuiltinOptionsSegmentSumOptions:
		return t.Value.(*SegmentSumOptionsT).Pack(builder)
	case BuiltinOptionsBatchMatMulOptions:
		return t.Value.(*BatchMatMulOptionsT).Pack(builder)
	case BuiltinOptionsCumsumOptions:
		return t.Value.(*CumsumOptionsT).Pack(builder)
	}
	return 0
}

func (rcv BuiltinOptions) UnPack(table flatbuffers.Table) *BuiltinOptionsT {
	switch rcv {
	case BuiltinOptionsConv2DOptions:
		x := Conv2DOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsConv2DOptions, Value: x.UnPack() }
	case BuiltinOptionsDepthwiseConv2DOptions:
		x := DepthwiseConv2DOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsDepthwiseConv2DOptions, Value: x.UnPack() }
	case BuiltinOptionsConcatEmbeddingsOptions:
		x := ConcatEmbeddingsOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsConcatEmbeddingsOptions, Value: x.UnPack() }
	case BuiltinOptionsLSHProjectionOptions:
		x := LSHProjectionOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLSHProjectionOptions, Value: x.UnPack() }
	case BuiltinOptionsPool2DOptions:
		x := Pool2DOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsPool2DOptions, Value: x.UnPack() }
	case BuiltinOptionsSVDFOptions:
		x := SVDFOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSVDFOptions, Value: x.UnPack() }
	case BuiltinOptionsRNNOptions:
		x := RNNOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsRNNOptions, Value: x.UnPack() }
	case BuiltinOptionsFullyConnectedOptions:
		x := FullyConnectedOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsFullyConnectedOptions, Value: x.UnPack() }
	case BuiltinOptionsSoftmaxOptions:
		x := SoftmaxOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSoftmaxOptions, Value: x.UnPack() }
	case BuiltinOptionsConcatenationOptions:
		x := ConcatenationOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsConcatenationOptions, Value: x.UnPack() }
	case BuiltinOptionsAddOptions:
		x := AddOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsAddOptions, Value: x.UnPack() }
	case BuiltinOptionsL2NormOptions:
		x := L2NormOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsL2NormOptions, Value: x.UnPack() }
	case BuiltinOptionsLocalResponseNormalizationOptions:
		x := LocalResponseNormalizationOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLocalResponseNormalizationOptions, Value: x.UnPack() }
	case BuiltinOptionsLSTMOptions:
		x := LSTMOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLSTMOptions, Value: x.UnPack() }
	case BuiltinOptionsResizeBilinearOptions:
		x := ResizeBilinearOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsResizeBilinearOptions, Value: x.UnPack() }
	case BuiltinOptionsCallOptions:
		x := CallOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsCallOptions, Value: x.UnPack() }
	case BuiltinOptionsReshapeOptions:
		x := ReshapeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsReshapeOptions, Value: x.UnPack() }
	case BuiltinOptionsSkipGramOptions:
		x := SkipGramOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSkipGramOptions, Value: x.UnPack() }
	case BuiltinOptionsSpaceToDepthOptions:
		x := SpaceToDepthOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSpaceToDepthOptions, Value: x.UnPack() }
	case BuiltinOptionsEmbeddingLookupSparseOptions:
		x := EmbeddingLookupSparseOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsEmbeddingLookupSparseOptions, Value: x.UnPack() }
	case BuiltinOptionsMulOptions:
		x := MulOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsMulOptions, Value: x.UnPack() }
	case BuiltinOptionsPadOptions:
		x := PadOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsPadOptions, Value: x.UnPack() }
	case BuiltinOptionsGatherOptions:
		x := GatherOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsGatherOptions, Value: x.UnPack() }
	case BuiltinOptionsBatchToSpaceNDOptions:
		x := BatchToSpaceNDOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsBatchToSpaceNDOptions, Value: x.UnPack() }
	case BuiltinOptionsSpaceToBatchNDOptions:
		x := SpaceToBatchNDOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSpaceToBatchNDOptions, Value: x.UnPack() }
	case BuiltinOptionsTransposeOptions:
		x := TransposeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsTransposeOptions, Value: x.UnPack() }
	case BuiltinOptionsReducerOptions:
		x := ReducerOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsReducerOptions, Value: x.UnPack() }
	case BuiltinOptionsSubOptions:
		x := SubOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSubOptions, Value: x.UnPack() }
	case BuiltinOptionsDivOptions:
		x := DivOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsDivOptions, Value: x.UnPack() }
	case BuiltinOptionsSqueezeOptions:
		x := SqueezeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSqueezeOptions, Value: x.UnPack() }
	case BuiltinOptionsSequenceRNNOptions:
		x := SequenceRNNOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSequenceRNNOptions, Value: x.UnPack() }
	case BuiltinOptionsStridedSliceOptions:
		x := StridedSliceOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsStridedSliceOptions, Value: x.UnPack() }
	case BuiltinOptionsExpOptions:
		x := ExpOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsExpOptions, Value: x.UnPack() }
	case BuiltinOptionsTopKV2Options:
		x := TopKV2Options{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsTopKV2Options, Value: x.UnPack() }
	case BuiltinOptionsSplitOptions:
		x := SplitOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSplitOptions, Value: x.UnPack() }
	case BuiltinOptionsLogSoftmaxOptions:
		x := LogSoftmaxOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLogSoftmaxOptions, Value: x.UnPack() }
	case BuiltinOptionsCastOptions:
		x := CastOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsCastOptions, Value: x.UnPack() }
	case BuiltinOptionsDequantizeOptions:
		x := DequantizeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsDequantizeOptions, Value: x.UnPack() }
	case BuiltinOptionsMaximumMinimumOptions:
		x := MaximumMinimumOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsMaximumMinimumOptions, Value: x.UnPack() }
	case BuiltinOptionsArgMaxOptions:
		x := ArgMaxOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsArgMaxOptions, Value: x.UnPack() }
	case BuiltinOptionsLessOptions:
		x := LessOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLessOptions, Value: x.UnPack() }
	case BuiltinOptionsNegOptions:
		x := NegOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsNegOptions, Value: x.UnPack() }
	case BuiltinOptionsPadV2Options:
		x := PadV2Options{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsPadV2Options, Value: x.UnPack() }
	case BuiltinOptionsGreaterOptions:
		x := GreaterOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsGreaterOptions, Value: x.UnPack() }
	case BuiltinOptionsGreaterEqualOptions:
		x := GreaterEqualOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsGreaterEqualOptions, Value: x.UnPack() }
	case BuiltinOptionsLessEqualOptions:
		x := LessEqualOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLessEqualOptions, Value: x.UnPack() }
	case BuiltinOptionsSelectOptions:
		x := SelectOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSelectOptions, Value: x.UnPack() }
	case BuiltinOptionsSliceOptions:
		x := SliceOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSliceOptions, Value: x.UnPack() }
	case BuiltinOptionsTransposeConvOptions:
		x := TransposeConvOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsTransposeConvOptions, Value: x.UnPack() }
	case BuiltinOptionsSparseToDenseOptions:
		x := SparseToDenseOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSparseToDenseOptions, Value: x.UnPack() }
	case BuiltinOptionsTileOptions:
		x := TileOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsTileOptions, Value: x.UnPack() }
	case BuiltinOptionsExpandDimsOptions:
		x := ExpandDimsOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsExpandDimsOptions, Value: x.UnPack() }
	case BuiltinOptionsEqualOptions:
		x := EqualOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsEqualOptions, Value: x.UnPack() }
	case BuiltinOptionsNotEqualOptions:
		x := NotEqualOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsNotEqualOptions, Value: x.UnPack() }
	case BuiltinOptionsShapeOptions:
		x := ShapeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsShapeOptions, Value: x.UnPack() }
	case BuiltinOptionsPowOptions:
		x := PowOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsPowOptions, Value: x.UnPack() }
	case BuiltinOptionsArgMinOptions:
		x := ArgMinOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsArgMinOptions, Value: x.UnPack() }
	case BuiltinOptionsFakeQuantOptions:
		x := FakeQuantOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsFakeQuantOptions, Value: x.UnPack() }
	case BuiltinOptionsPackOptions:
		x := PackOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsPackOptions, Value: x.UnPack() }
	case BuiltinOptionsLogicalOrOptions:
		x := LogicalOrOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLogicalOrOptions, Value: x.UnPack() }
	case BuiltinOptionsOneHotOptions:
		x := OneHotOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsOneHotOptions, Value: x.UnPack() }
	case BuiltinOptionsLogicalAndOptions:
		x := LogicalAndOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLogicalAndOptions, Value: x.UnPack() }
	case BuiltinOptionsLogicalNotOptions:
		x := LogicalNotOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLogicalNotOptions, Value: x.UnPack() }
	case BuiltinOptionsUnpackOptions:
		x := UnpackOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsUnpackOptions, Value: x.UnPack() }
	case BuiltinOptionsFloorDivOptions:
		x := FloorDivOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsFloorDivOptions, Value: x.UnPack() }
	case BuiltinOptionsSquareOptions:
		x := SquareOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSquareOptions, Value: x.UnPack() }
	case BuiltinOptionsZerosLikeOptions:
		x := ZerosLikeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsZerosLikeOptions, Value: x.UnPack() }
	case BuiltinOptionsFillOptions:
		x := FillOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsFillOptions, Value: x.UnPack() }
	case BuiltinOptionsBidirectionalSequenceLSTMOptions:
		x := BidirectionalSequenceLSTMOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsBidirectionalSequenceLSTMOptions, Value: x.UnPack() }
	case BuiltinOptionsBidirectionalSequenceRNNOptions:
		x := BidirectionalSequenceRNNOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsBidirectionalSequenceRNNOptions, Value: x.UnPack() }
	case BuiltinOptionsUnidirectionalSequenceLSTMOptions:
		x := UnidirectionalSequenceLSTMOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsUnidirectionalSequenceLSTMOptions, Value: x.UnPack() }
	case BuiltinOptionsFloorModOptions:
		x := FloorModOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsFloorModOptions, Value: x.UnPack() }
	case BuiltinOptionsRangeOptions:
		x := RangeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsRangeOptions, Value: x.UnPack() }
	case BuiltinOptionsResizeNearestNeighborOptions:
		x := ResizeNearestNeighborOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsResizeNearestNeighborOptions, Value: x.UnPack() }
	case BuiltinOptionsLeakyReluOptions:
		x := LeakyReluOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsLeakyReluOptions, Value: x.UnPack() }
	case BuiltinOptionsSquaredDifferenceOptions:
		x := SquaredDifferenceOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSquaredDifferenceOptions, Value: x.UnPack() }
	case BuiltinOptionsMirrorPadOptions:
		x := MirrorPadOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsMirrorPadOptions, Value: x.UnPack() }
	case BuiltinOptionsAbsOptions:
		x := AbsOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsAbsOptions, Value: x.UnPack() }
	case BuiltinOptionsSplitVOptions:
		x := SplitVOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSplitVOptions, Value: x.UnPack() }
	case BuiltinOptionsUniqueOptions:
		x := UniqueOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsUniqueOptions, Value: x.UnPack() }
	case BuiltinOptionsReverseV2Options:
		x := ReverseV2Options{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsReverseV2Options, Value: x.UnPack() }
	case BuiltinOptionsAddNOptions:
		x := AddNOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsAddNOptions, Value: x.UnPack() }
	case BuiltinOptionsGatherNdOptions:
		x := GatherNdOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsGatherNdOptions, Value: x.UnPack() }
	case BuiltinOptionsCosOptions:
		x := CosOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsCosOptions, Value: x.UnPack() }
	case BuiltinOptionsWhereOptions:
		x := WhereOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsWhereOptions, Value: x.UnPack() }
	case BuiltinOptionsRankOptions:
		x := RankOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsRankOptions, Value: x.UnPack() }
	case BuiltinOptionsReverseSequenceOptions:
		x := ReverseSequenceOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsReverseSequenceOptions, Value: x.UnPack() }
	case BuiltinOptionsMatrixDiagOptions:
		x := MatrixDiagOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsMatrixDiagOptions, Value: x.UnPack() }
	case BuiltinOptionsQuantizeOptions:
		x := QuantizeOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsQuantizeOptions, Value: x.UnPack() }
	case BuiltinOptionsMatrixSetDiagOptions:
		x := MatrixSetDiagOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsMatrixSetDiagOptions, Value: x.UnPack() }
	case BuiltinOptionsHardSwishOptions:
		x := HardSwishOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsHardSwishOptions, Value: x.UnPack() }
	case BuiltinOptionsIfOptions:
		x := IfOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsIfOptions, Value: x.UnPack() }
	case BuiltinOptionsWhileOptions:
		x := WhileOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsWhileOptions, Value: x.UnPack() }
	case BuiltinOptionsDepthToSpaceOptions:
		x := DepthToSpaceOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsDepthToSpaceOptions, Value: x.UnPack() }
	case BuiltinOptionsNonMaxSuppressionV4Options:
		x := NonMaxSuppressionV4Options{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsNonMaxSuppressionV4Options, Value: x.UnPack() }
	case BuiltinOptionsNonMaxSuppressionV5Options:
		x := NonMaxSuppressionV5Options{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsNonMaxSuppressionV5Options, Value: x.UnPack() }
	case BuiltinOptionsScatterNdOptions:
		x := ScatterNdOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsScatterNdOptions, Value: x.UnPack() }
	case BuiltinOptionsSelectV2Options:
		x := SelectV2Options{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSelectV2Options, Value: x.UnPack() }
	case BuiltinOptionsDensifyOptions:
		x := DensifyOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsDensifyOptions, Value: x.UnPack() }
	case BuiltinOptionsSegmentSumOptions:
		x := SegmentSumOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsSegmentSumOptions, Value: x.UnPack() }
	case BuiltinOptionsBatchMatMulOptions:
		x := BatchMatMulOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsBatchMatMulOptions, Value: x.UnPack() }
	case BuiltinOptionsCumsumOptions:
		x := CumsumOptions{_tab: table}
		return &BuiltinOptionsT{ Type: BuiltinOptionsCumsumOptions, Value: x.UnPack() }
	}
	return nil
}
