// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CumsumOptionsT struct {
	Exclusive bool
	Reverse bool
}

func (t *CumsumOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	CumsumOptionsStart(builder)
	CumsumOptionsAddExclusive(builder, t.Exclusive)
	CumsumOptionsAddReverse(builder, t.Reverse)
	return CumsumOptionsEnd(builder)
}

func (rcv *CumsumOptions) UnPackTo(t *CumsumOptionsT) {
	t.Exclusive = rcv.Exclusive()
	t.Reverse = rcv.Reverse()
}

func (rcv *CumsumOptions) UnPack() *CumsumOptionsT {
	if rcv == nil { return nil }
	t := &CumsumOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type CumsumOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsCumsumOptions(buf []byte, offset flatbuffers.UOffsetT) *CumsumOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CumsumOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CumsumOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CumsumOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CumsumOptions) Exclusive() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CumsumOptions) MutateExclusive(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *CumsumOptions) Reverse() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CumsumOptions) MutateReverse(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func CumsumOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CumsumOptionsAddExclusive(builder *flatbuffers.Builder, exclusive bool) {
	builder.PrependBoolSlot(0, exclusive, false)
}
func CumsumOptionsAddReverse(builder *flatbuffers.Builder, reverse bool) {
	builder.PrependBoolSlot(1, reverse, false)
}
func CumsumOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
