// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DensifyOptionsT struct {
}

func (t *DensifyOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	DensifyOptionsStart(builder)
	return DensifyOptionsEnd(builder)
}

func (rcv *DensifyOptions) UnPackTo(t *DensifyOptionsT) {
}

func (rcv *DensifyOptions) UnPack() *DensifyOptionsT {
	if rcv == nil { return nil }
	t := &DensifyOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type DensifyOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsDensifyOptions(buf []byte, offset flatbuffers.UOffsetT) *DensifyOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DensifyOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DensifyOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DensifyOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func DensifyOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DensifyOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
