// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DequantizeOptionsT struct {
}

func (t *DequantizeOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	DequantizeOptionsStart(builder)
	return DequantizeOptionsEnd(builder)
}

func (rcv *DequantizeOptions) UnPackTo(t *DequantizeOptionsT) {
}

func (rcv *DequantizeOptions) UnPack() *DequantizeOptionsT {
	if rcv == nil { return nil }
	t := &DequantizeOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type DequantizeOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsDequantizeOptions(buf []byte, offset flatbuffers.UOffsetT) *DequantizeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DequantizeOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DequantizeOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DequantizeOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func DequantizeOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DequantizeOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
