// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExpandDimsOptionsT struct {
}

func (t *ExpandDimsOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ExpandDimsOptionsStart(builder)
	return ExpandDimsOptionsEnd(builder)
}

func (rcv *ExpandDimsOptions) UnPackTo(t *ExpandDimsOptionsT) {
}

func (rcv *ExpandDimsOptions) UnPack() *ExpandDimsOptionsT {
	if rcv == nil { return nil }
	t := &ExpandDimsOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type ExpandDimsOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsExpandDimsOptions(buf []byte, offset flatbuffers.UOffsetT) *ExpandDimsOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExpandDimsOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ExpandDimsOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExpandDimsOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func ExpandDimsOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ExpandDimsOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
