// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FloorModOptionsT struct {
}

func (t *FloorModOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	FloorModOptionsStart(builder)
	return FloorModOptionsEnd(builder)
}

func (rcv *FloorModOptions) UnPackTo(t *FloorModOptionsT) {
}

func (rcv *FloorModOptions) UnPack() *FloorModOptionsT {
	if rcv == nil { return nil }
	t := &FloorModOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type FloorModOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsFloorModOptions(buf []byte, offset flatbuffers.UOffsetT) *FloorModOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FloorModOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FloorModOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FloorModOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func FloorModOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func FloorModOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
