// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GatherNdOptionsT struct {
}

func (t *GatherNdOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	GatherNdOptionsStart(builder)
	return GatherNdOptionsEnd(builder)
}

func (rcv *GatherNdOptions) UnPackTo(t *GatherNdOptionsT) {
}

func (rcv *GatherNdOptions) UnPack() *GatherNdOptionsT {
	if rcv == nil { return nil }
	t := &GatherNdOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type GatherNdOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsGatherNdOptions(buf []byte, offset flatbuffers.UOffsetT) *GatherNdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GatherNdOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GatherNdOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GatherNdOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func GatherNdOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GatherNdOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
