// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GreaterOptionsT struct {
}

func (t *GreaterOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	GreaterOptionsStart(builder)
	return GreaterOptionsEnd(builder)
}

func (rcv *GreaterOptions) UnPackTo(t *GreaterOptionsT) {
}

func (rcv *GreaterOptions) UnPack() *GreaterOptionsT {
	if rcv == nil { return nil }
	t := &GreaterOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type GreaterOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsGreaterOptions(buf []byte, offset flatbuffers.UOffsetT) *GreaterOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GreaterOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GreaterOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GreaterOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func GreaterOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GreaterOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
