// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HardSwishOptionsT struct {
}

func (t *HardSwishOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	HardSwishOptionsStart(builder)
	return HardSwishOptionsEnd(builder)
}

func (rcv *HardSwishOptions) UnPackTo(t *HardSwishOptionsT) {
}

func (rcv *HardSwishOptions) UnPack() *HardSwishOptionsT {
	if rcv == nil { return nil }
	t := &HardSwishOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type HardSwishOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsHardSwishOptions(buf []byte, offset flatbuffers.UOffsetT) *HardSwishOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HardSwishOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *HardSwishOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HardSwishOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func HardSwishOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HardSwishOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
