// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type L2NormOptionsT struct {
	FusedActivationFunction ActivationFunctionType
}

func (t *L2NormOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	L2NormOptionsStart(builder)
	L2NormOptionsAddFusedActivationFunction(builder, t.FusedActivationFunction)
	return L2NormOptionsEnd(builder)
}

func (rcv *L2NormOptions) UnPackTo(t *L2NormOptionsT) {
	t.FusedActivationFunction = rcv.FusedActivationFunction()
}

func (rcv *L2NormOptions) UnPack() *L2NormOptionsT {
	if rcv == nil { return nil }
	t := &L2NormOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type L2NormOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsL2NormOptions(buf []byte, offset flatbuffers.UOffsetT) *L2NormOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &L2NormOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *L2NormOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *L2NormOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *L2NormOptions) FusedActivationFunction() ActivationFunctionType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ActivationFunctionType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *L2NormOptions) MutateFusedActivationFunction(n ActivationFunctionType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func L2NormOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func L2NormOptionsAddFusedActivationFunction(builder *flatbuffers.Builder, fusedActivationFunction ActivationFunctionType) {
	builder.PrependInt8Slot(0, int8(fusedActivationFunction), 0)
}
func L2NormOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
