// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LeakyReluOptionsT struct {
	Alpha float32
}

func (t *LeakyReluOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	LeakyReluOptionsStart(builder)
	LeakyReluOptionsAddAlpha(builder, t.Alpha)
	return LeakyReluOptionsEnd(builder)
}

func (rcv *LeakyReluOptions) UnPackTo(t *LeakyReluOptionsT) {
	t.Alpha = rcv.Alpha()
}

func (rcv *LeakyReluOptions) UnPack() *LeakyReluOptionsT {
	if rcv == nil { return nil }
	t := &LeakyReluOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type LeakyReluOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsLeakyReluOptions(buf []byte, offset flatbuffers.UOffsetT) *LeakyReluOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LeakyReluOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LeakyReluOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LeakyReluOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LeakyReluOptions) Alpha() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LeakyReluOptions) MutateAlpha(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func LeakyReluOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LeakyReluOptionsAddAlpha(builder *flatbuffers.Builder, alpha float32) {
	builder.PrependFloat32Slot(0, alpha, 0.0)
}
func LeakyReluOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
