// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LessOptionsT struct {
}

func (t *LessOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	LessOptionsStart(builder)
	return LessOptionsEnd(builder)
}

func (rcv *LessOptions) UnPackTo(t *LessOptionsT) {
}

func (rcv *LessOptions) UnPack() *LessOptionsT {
	if rcv == nil { return nil }
	t := &LessOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type LessOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsLessOptions(buf []byte, offset flatbuffers.UOffsetT) *LessOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LessOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LessOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LessOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func LessOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func LessOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
