// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogicalOrOptionsT struct {
}

func (t *LogicalOrOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	LogicalOrOptionsStart(builder)
	return LogicalOrOptionsEnd(builder)
}

func (rcv *LogicalOrOptions) UnPackTo(t *LogicalOrOptionsT) {
}

func (rcv *LogicalOrOptions) UnPack() *LogicalOrOptionsT {
	if rcv == nil { return nil }
	t := &LogicalOrOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type LogicalOrOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsLogicalOrOptions(buf []byte, offset flatbuffers.UOffsetT) *LogicalOrOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogicalOrOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LogicalOrOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogicalOrOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func LogicalOrOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func LogicalOrOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
