// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogSoftmaxOptionsT struct {
}

func (t *LogSoftmaxOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	LogSoftmaxOptionsStart(builder)
	return LogSoftmaxOptionsEnd(builder)
}

func (rcv *LogSoftmaxOptions) UnPackTo(t *LogSoftmaxOptionsT) {
}

func (rcv *LogSoftmaxOptions) UnPack() *LogSoftmaxOptionsT {
	if rcv == nil { return nil }
	t := &LogSoftmaxOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type LogSoftmaxOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsLogSoftmaxOptions(buf []byte, offset flatbuffers.UOffsetT) *LogSoftmaxOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogSoftmaxOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LogSoftmaxOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogSoftmaxOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func LogSoftmaxOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func LogSoftmaxOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
