// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LSHProjectionOptionsT struct {
	Type LSHProjectionType
}

func (t *LSHProjectionOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	LSHProjectionOptionsStart(builder)
	LSHProjectionOptionsAddType(builder, t.Type)
	return LSHProjectionOptionsEnd(builder)
}

func (rcv *LSHProjectionOptions) UnPackTo(t *LSHProjectionOptionsT) {
	t.Type = rcv.Type()
}

func (rcv *LSHProjectionOptions) UnPack() *LSHProjectionOptionsT {
	if rcv == nil { return nil }
	t := &LSHProjectionOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type LSHProjectionOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsLSHProjectionOptions(buf []byte, offset flatbuffers.UOffsetT) *LSHProjectionOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LSHProjectionOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LSHProjectionOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LSHProjectionOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LSHProjectionOptions) Type() LSHProjectionType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return LSHProjectionType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *LSHProjectionOptions) MutateType(n LSHProjectionType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func LSHProjectionOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LSHProjectionOptionsAddType(builder *flatbuffers.Builder, type_ LSHProjectionType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func LSHProjectionOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
