// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NonMaxSuppressionV4OptionsT struct {
}

func (t *NonMaxSuppressionV4OptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	NonMaxSuppressionV4OptionsStart(builder)
	return NonMaxSuppressionV4OptionsEnd(builder)
}

func (rcv *NonMaxSuppressionV4Options) UnPackTo(t *NonMaxSuppressionV4OptionsT) {
}

func (rcv *NonMaxSuppressionV4Options) UnPack() *NonMaxSuppressionV4OptionsT {
	if rcv == nil { return nil }
	t := &NonMaxSuppressionV4OptionsT{}
	rcv.UnPackTo(t)
	return t
}

type NonMaxSuppressionV4Options struct {
	_tab flatbuffers.Table
}

func GetRootAsNonMaxSuppressionV4Options(buf []byte, offset flatbuffers.UOffsetT) *NonMaxSuppressionV4Options {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NonMaxSuppressionV4Options{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NonMaxSuppressionV4Options) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NonMaxSuppressionV4Options) Table() flatbuffers.Table {
	return rcv._tab
}

func NonMaxSuppressionV4OptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func NonMaxSuppressionV4OptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
