// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PadOptionsT struct {
}

func (t *PadOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	PadOptionsStart(builder)
	return PadOptionsEnd(builder)
}

func (rcv *PadOptions) UnPackTo(t *PadOptionsT) {
}

func (rcv *PadOptions) UnPack() *PadOptionsT {
	if rcv == nil { return nil }
	t := &PadOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type PadOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsPadOptions(buf []byte, offset flatbuffers.UOffsetT) *PadOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PadOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PadOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PadOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func PadOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PadOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
