// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PadV2OptionsT struct {
}

func (t *PadV2OptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	PadV2OptionsStart(builder)
	return PadV2OptionsEnd(builder)
}

func (rcv *PadV2Options) UnPackTo(t *PadV2OptionsT) {
}

func (rcv *PadV2Options) UnPack() *PadV2OptionsT {
	if rcv == nil { return nil }
	t := &PadV2OptionsT{}
	rcv.UnPackTo(t)
	return t
}

type PadV2Options struct {
	_tab flatbuffers.Table
}

func GetRootAsPadV2Options(buf []byte, offset flatbuffers.UOffsetT) *PadV2Options {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PadV2Options{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PadV2Options) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PadV2Options) Table() flatbuffers.Table {
	return rcv._tab
}

func PadV2OptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PadV2OptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
