// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PowOptionsT struct {
}

func (t *PowOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	PowOptionsStart(builder)
	return PowOptionsEnd(builder)
}

func (rcv *PowOptions) UnPackTo(t *PowOptionsT) {
}

func (rcv *PowOptions) UnPack() *PowOptionsT {
	if rcv == nil { return nil }
	t := &PowOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type PowOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsPowOptions(buf []byte, offset flatbuffers.UOffsetT) *PowOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PowOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PowOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PowOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func PowOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PowOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
