// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RankOptionsT struct {
}

func (t *RankOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	RankOptionsStart(builder)
	return RankOptionsEnd(builder)
}

func (rcv *RankOptions) UnPackTo(t *RankOptionsT) {
}

func (rcv *RankOptions) UnPack() *RankOptionsT {
	if rcv == nil { return nil }
	t := &RankOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type RankOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsRankOptions(buf []byte, offset flatbuffers.UOffsetT) *RankOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RankOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RankOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RankOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func RankOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RankOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
