// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReducerOptionsT struct {
	KeepDims bool
}

func (t *ReducerOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ReducerOptionsStart(builder)
	ReducerOptionsAddKeepDims(builder, t.KeepDims)
	return ReducerOptionsEnd(builder)
}

func (rcv *ReducerOptions) UnPackTo(t *ReducerOptionsT) {
	t.KeepDims = rcv.KeepDims()
}

func (rcv *ReducerOptions) UnPack() *ReducerOptionsT {
	if rcv == nil { return nil }
	t := &ReducerOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type ReducerOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsReducerOptions(buf []byte, offset flatbuffers.UOffsetT) *ReducerOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReducerOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ReducerOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReducerOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReducerOptions) KeepDims() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ReducerOptions) MutateKeepDims(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func ReducerOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReducerOptionsAddKeepDims(builder *flatbuffers.Builder, keepDims bool) {
	builder.PrependBoolSlot(0, keepDims, false)
}
func ReducerOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
