// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReverseV2OptionsT struct {
}

func (t *ReverseV2OptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ReverseV2OptionsStart(builder)
	return ReverseV2OptionsEnd(builder)
}

func (rcv *ReverseV2Options) UnPackTo(t *ReverseV2OptionsT) {
}

func (rcv *ReverseV2Options) UnPack() *ReverseV2OptionsT {
	if rcv == nil { return nil }
	t := &ReverseV2OptionsT{}
	rcv.UnPackTo(t)
	return t
}

type ReverseV2Options struct {
	_tab flatbuffers.Table
}

func GetRootAsReverseV2Options(buf []byte, offset flatbuffers.UOffsetT) *ReverseV2Options {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReverseV2Options{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ReverseV2Options) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReverseV2Options) Table() flatbuffers.Table {
	return rcv._tab
}

func ReverseV2OptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ReverseV2OptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
