// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScatterNdOptionsT struct {
}

func (t *ScatterNdOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ScatterNdOptionsStart(builder)
	return ScatterNdOptionsEnd(builder)
}

func (rcv *ScatterNdOptions) UnPackTo(t *ScatterNdOptionsT) {
}

func (rcv *ScatterNdOptions) UnPack() *ScatterNdOptionsT {
	if rcv == nil { return nil }
	t := &ScatterNdOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type ScatterNdOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsScatterNdOptions(buf []byte, offset flatbuffers.UOffsetT) *ScatterNdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScatterNdOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ScatterNdOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScatterNdOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func ScatterNdOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ScatterNdOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
