// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SliceOptionsT struct {
}

func (t *SliceOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	SliceOptionsStart(builder)
	return SliceOptionsEnd(builder)
}

func (rcv *SliceOptions) UnPackTo(t *SliceOptionsT) {
}

func (rcv *SliceOptions) UnPack() *SliceOptionsT {
	if rcv == nil { return nil }
	t := &SliceOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type SliceOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSliceOptions(buf []byte, offset flatbuffers.UOffsetT) *SliceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SliceOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SliceOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SliceOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func SliceOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SliceOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
