// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpaceToBatchNDOptionsT struct {
}

func (t *SpaceToBatchNDOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	SpaceToBatchNDOptionsStart(builder)
	return SpaceToBatchNDOptionsEnd(builder)
}

func (rcv *SpaceToBatchNDOptions) UnPackTo(t *SpaceToBatchNDOptionsT) {
}

func (rcv *SpaceToBatchNDOptions) UnPack() *SpaceToBatchNDOptionsT {
	if rcv == nil { return nil }
	t := &SpaceToBatchNDOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type SpaceToBatchNDOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSpaceToBatchNDOptions(buf []byte, offset flatbuffers.UOffsetT) *SpaceToBatchNDOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpaceToBatchNDOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SpaceToBatchNDOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpaceToBatchNDOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func SpaceToBatchNDOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SpaceToBatchNDOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
