// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SquareOptionsT struct {
}

func (t *SquareOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	SquareOptionsStart(builder)
	return SquareOptionsEnd(builder)
}

func (rcv *SquareOptions) UnPackTo(t *SquareOptionsT) {
}

func (rcv *SquareOptions) UnPack() *SquareOptionsT {
	if rcv == nil { return nil }
	t := &SquareOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type SquareOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSquareOptions(buf []byte, offset flatbuffers.UOffsetT) *SquareOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SquareOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SquareOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SquareOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func SquareOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SquareOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
