// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransposeOptionsT struct {
}

func (t *TransposeOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	TransposeOptionsStart(builder)
	return TransposeOptionsEnd(builder)
}

func (rcv *TransposeOptions) UnPackTo(t *TransposeOptionsT) {
}

func (rcv *TransposeOptions) UnPack() *TransposeOptionsT {
	if rcv == nil { return nil }
	t := &TransposeOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type TransposeOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsTransposeOptions(buf []byte, offset flatbuffers.UOffsetT) *TransposeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransposeOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TransposeOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransposeOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func TransposeOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func TransposeOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
