// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WhileOptionsT struct {
	CondSubgraphIndex int32
	BodySubgraphIndex int32
}

func (t *WhileOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	WhileOptionsStart(builder)
	WhileOptionsAddCondSubgraphIndex(builder, t.CondSubgraphIndex)
	WhileOptionsAddBodySubgraphIndex(builder, t.BodySubgraphIndex)
	return WhileOptionsEnd(builder)
}

func (rcv *WhileOptions) UnPackTo(t *WhileOptionsT) {
	t.CondSubgraphIndex = rcv.CondSubgraphIndex()
	t.BodySubgraphIndex = rcv.BodySubgraphIndex()
}

func (rcv *WhileOptions) UnPack() *WhileOptionsT {
	if rcv == nil { return nil }
	t := &WhileOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type WhileOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsWhileOptions(buf []byte, offset flatbuffers.UOffsetT) *WhileOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WhileOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WhileOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WhileOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WhileOptions) CondSubgraphIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WhileOptions) MutateCondSubgraphIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *WhileOptions) BodySubgraphIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WhileOptions) MutateBodySubgraphIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func WhileOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func WhileOptionsAddCondSubgraphIndex(builder *flatbuffers.Builder, condSubgraphIndex int32) {
	builder.PrependInt32Slot(0, condSubgraphIndex, 0)
}
func WhileOptionsAddBodySubgraphIndex(builder *flatbuffers.Builder, bodySubgraphIndex int32) {
	builder.PrependInt32Slot(1, bodySubgraphIndex, 0)
}
func WhileOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
