// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ZerosLikeOptionsT struct {
}

func (t *ZerosLikeOptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ZerosLikeOptionsStart(builder)
	return ZerosLikeOptionsEnd(builder)
}

func (rcv *ZerosLikeOptions) UnPackTo(t *ZerosLikeOptionsT) {
}

func (rcv *ZerosLikeOptions) UnPack() *ZerosLikeOptionsT {
	if rcv == nil { return nil }
	t := &ZerosLikeOptionsT{}
	rcv.UnPackTo(t)
	return t
}

type ZerosLikeOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsZerosLikeOptions(buf []byte, offset flatbuffers.UOffsetT) *ZerosLikeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ZerosLikeOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ZerosLikeOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ZerosLikeOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func ZerosLikeOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ZerosLikeOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
